Bug/epgr 8
diging/grazer-ep pull request #23
Opened 2017-11-20 21:33 UTC by Mihika0409

Removed the empty link that was being shown if there was no equalTo concept.

2018-01-04 22:28 UTC, jdamerow requested changes

2018-01-04 22:28 UTC, jdamerow commented on grazer/src/main/webapp/WEB-INF/views/person.jsp
> +			<c:if test="${listVar != '[]'}">
let's remove this test. The equalTo field does sometimes contain [] but it's a mistake and shouldn't  be there. This way we can see it and fix it in conceptpower.

2018-01-08 16:51 UTC, jdamerow approved these changes

2018-01-08 16:52 UTC, jdamerow commented
ok to test

2018-01-08 16:53 UTC, jdamerow commented
retest this please

2018-01-08 17:59 UTC, jdamerow commented
retest this please

2018-01-08 18:09 UTC, abhikrish503501 approved these changes

2018-01-08 19:26 UTC, merged