Story/epgr 12
diging/grazer-ep pull request #24
Opened 2017-11-27 22:41 UTC by Mihika0409

Graph on home page should scroll down as user scrolls through the list of people

2018-01-04 17:09 UTC, jdamerow requested changes

2018-01-04 17:09 UTC, jdamerow commented on grazer/src/main/webapp/WEB-INF/views/home.jsp
>  $(document).ready(function() {
lets keep the 4 spaces indentation

2018-01-04 17:09 UTC, jdamerow commented
ok to test

2018-01-04 17:21 UTC, jdamerow requested changes

2018-01-04 17:21 UTC, jdamerow commented on grazer/src/main/webapp/WEB-INF/views/home.jsp
> +        window.onresize = function(){ location.reload(); }
does this reload the page as soon as the user resizes the window? the user would loose on whatever part he zoomed in on. that would be pretty annoying.

2018-02-06 17:09 UTC, chiraag-subramanian commented on grazer/src/main/webapp/WEB-INF/views/home.jsp
> +
Do we need the style position:relative for .graph-outer. The position:relative tag is accompanied by either of these offset : top, bottom, right or left
https://www.w3schools.com/css/css_positioning.asp

2018-02-06 17:32 UTC, abhikrish503501 approved these changes

2018-02-06 17:58 UTC, chiraag-subramanian approved these changes

2018-02-06 18:26 UTC, jdamerow commented
formatting is still not taken care of

2018-02-20 16:28 UTC, jdamerow commented
ok to test

2018-02-20 16:39 UTC, jdamerow commented
Instead of the graph being fixed, can we please simply make the name list scrollable (every stays, just the names scroll)? The way it is right now looks funny because there is a lot of white space above the graph.

2018-02-20 18:24 UTC, jdamerow commented
ok to test

2018-02-20 18:28 UTC, jdamerow approved these changes

2018-02-20 18:28 UTC, merged